// Loader for the soldier name bank. The JSON is generated by
// `scripts/generate-name-bank.ts` and committed to the repo.
//
// Theme ids are assigned by sorting the JSON's theme keys alphabetically and
// numbering them 0..N-1, so the mapping is deterministic.

import bank from './name-bank.json';

interface ThemePools {
  firstNames: string[];
  lastNames: string[];
  hometowns: string[];
}

interface NameBank {
  version: number;
  themes: Record<string, ThemePools>;
}

const BANK = bank as NameBank;

const sortedThemeNames: readonly string[] = Object.keys(BANK.themes).sort();

const themeIdMap: Record<string, number> = {};
for (let i = 0; i < sortedThemeNames.length; i++) {
  themeIdMap[sortedThemeNames[i] as string] = i;
}

export const themeIds: Readonly<Record<string, number>> = themeIdMap;
export const themeNames: readonly string[] = sortedThemeNames;

const PLACEHOLDER = '?';

function poolsFor(themeId: number): ThemePools | undefined {
  if (!Number.isInteger(themeId) || themeId < 0 || themeId >= sortedThemeNames.length) {
    return undefined;
  }
  const name = sortedThemeNames[themeId] as string;
  return BANK.themes[name];
}

function lookup(pool: string[] | undefined, idx: number): string {
  if (!pool) return PLACEHOLDER;
  if (!Number.isInteger(idx) || idx < 0 || idx >= pool.length) return PLACEHOLDER;
  const v = pool[idx];
  return typeof v === 'string' && v.length > 0 ? v : PLACEHOLDER;
}

/** Resolve a theme name to its numeric id, or -1 if unknown. */
export function themeIdOf(name: string): number {
  const id = themeIdMap[name];
  return typeof id === 'number' ? id : -1;
}

/** Resolve a numeric theme id back to its name, or '?' if out of range. */
export function themeNameOf(id: number): string {
  if (!Number.isInteger(id) || id < 0 || id >= sortedThemeNames.length) return PLACEHOLDER;
  return sortedThemeNames[id] as string;
}

export function firstNameOf(themeId: number, idx: number): string {
  return lookup(poolsFor(themeId)?.firstNames, idx);
}

export function lastNameOf(themeId: number, idx: number): string {
  return lookup(poolsFor(themeId)?.lastNames, idx);
}

export function hometownOf(themeId: number, idx: number): string {
  return lookup(poolsFor(themeId)?.hometowns, idx);
}

/** Pool sizes for a theme. Returns zeros for unknown themeId. */
export function poolSizes(themeId: number): { first: number; last: number; town: number } {
  const pools = poolsFor(themeId);
  if (!pools) return { first: 0, last: 0, town: 0 };
  return {
    first: pools.firstNames.length,
    last: pools.lastNames.length,
    town: pools.hometowns.length,
  };
}
